import { HeadContent, Scripts, createRootRoute } from "@tanstack/react-router"
import Footer from "../components/Footer"
import Header from "../components/Header"

import appCss from "../styles.css?url"

const THEME_INIT_SCRIPT = `(function(){try{var stored=window.localStorage.getItem('theme');var mode=(stored==='light'||stored==='dark'||stored==='auto')?stored:'auto';var prefersDark=window.matchMedia('(prefers-color-scheme: dark)').matches;var resolved=mode==='auto'?(prefersDark?'dark':'light'):mode;var root=document.documentElement;root.classList.remove('light','dark');root.classList.add(resolved);if(mode==='auto'){root.removeAttribute('data-theme')}else{root.setAttribute('data-theme',mode)}root.style.colorScheme=resolved;}catch(e){}})();`
const SITE_URL = "https://adilkairolla.dev/five-designs"
const SITE_TITLE = "Five Designs"
const SITE_DESCRIPTION =
  "A React reader-design showcase comparing five-screen experiments generated by different tools and models."
const OG_IMAGE_URL = `${SITE_URL}/og-image.png`

export const Route = createRootRoute({
  head: () => ({
    meta: [
      {
        charSet: 'utf-8',
      },
      {
        name: 'viewport',
        content: 'width=device-width, initial-scale=1',
      },
      {
        title: SITE_TITLE,
      },
      {
        name: "description",
        content: SITE_DESCRIPTION,
      },
      {
        property: "og:type",
        content: "website",
      },
      {
        property: "og:url",
        content: SITE_URL,
      },
      {
        property: "og:title",
        content: SITE_TITLE,
      },
      {
        property: "og:description",
        content: SITE_DESCRIPTION,
      },
      {
        property: "og:image",
        content: OG_IMAGE_URL,
      },
      {
        property: "og:image:width",
        content: "1200",
      },
      {
        property: "og:image:height",
        content: "630",
      },
      {
        name: "twitter:card",
        content: "summary_large_image",
      },
      {
        name: "twitter:title",
        content: SITE_TITLE,
      },
      {
        name: "twitter:description",
        content: SITE_DESCRIPTION,
      },
      {
        name: "twitter:image",
        content: OG_IMAGE_URL,
      },
    ],
    links: [
      {
        rel: "icon",
        href: "/five-designs/favicon.ico",
        sizes: "any",
      },
      {
        rel: "icon",
        type: "image/png",
        href: "/five-designs/favicon-32x32.png",
        sizes: "32x32",
      },
      {
        rel: "icon",
        type: "image/png",
        href: "/five-designs/favicon-16x16.png",
        sizes: "16x16",
      },
      {
        rel: "apple-touch-icon",
        href: "/five-designs/apple-touch-icon.png",
        sizes: "180x180",
      },
      {
        rel: "manifest",
        href: "/five-designs/manifest.json",
      },
      {
        rel: 'stylesheet',
        href: appCss,
      },
    ],
  }),
  notFoundComponent: NotFound,
  shellComponent: RootDocument,
})

function NotFound() {
  return (
    <main className="page-wrap flex min-h-[70svh] flex-col justify-center gap-5 px-4 py-16">
      <p className="m-0 text-sm font-medium text-muted-foreground">404</p>
      <h1 className="display-title m-0 max-w-2xl text-5xl leading-none font-semibold text-foreground md:text-7xl">
        Project route not found
      </h1>
      <p className="m-0 max-w-xl text-base leading-7 text-muted-foreground">
        This path is not part of the Five Designs app shell. Use the gallery to
        open one of the embedded project previews.
      </p>
      <a
        href="/five-designs/#projects"
        className="inline-flex h-9 w-fit items-center justify-center rounded-lg border border-input bg-popover px-3 text-sm font-medium text-foreground shadow-xs/5 transition hover:bg-accent/50"
      >
        Back to gallery
      </a>
    </main>
  )
}

function RootDocument({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <script dangerouslySetInnerHTML={{ __html: THEME_INIT_SCRIPT }} />
        <HeadContent />
      </head>
      <body className="relative font-sans antialiased [overflow-wrap:anywhere] selection:bg-primary/15">
        <div className="isolate relative flex min-h-svh flex-col">
          <Header />
          <div className="flex-1">{children}</div>
          <Footer />
        </div>
        <Scripts />
      </body>
    </html>
  )
}
